name: Deploy Monitoring Services to EC2

on:
  push:
    paths:
      - 'monitoring/**' 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Deploy monitoring to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker compose up -d prometheus grafana